[package]
name = "caves"
version = "0.1.0"
authors = ["Sunjay Varma <varma.sunjay@gmail.com>"]
edition = "2018"

[dependencies]
specs = "*"
specs-derive = "*"
shred = "*"
shred-derive = "*"
rand = "0.6"
base64 = "0.11"
lazy_static = "1.2"
colored = "1.9"
rayon = "1.1"
component_group = "1.0"
rusttype = "0.7"

[dependencies.sdl2]
version = "*"
default-features = false
features = ["image"]
